### ISSUE TITLE
create ResultSet class (leverage common functions pulled out of DataSet)

### ISSUE THREAD

**Issue by BradReesWork** [rapidsai/cugraph#3367] opened 2023-03-24 17:25 UTC
Take common functions from DataSets and create a similar class but one that loads result sets used for validation in test

**Comment by rlratzel** [comment] 2023-06-24 20:03
duplicate of https://github.com/rapidsai/cugraph/issues/2416

**Closed by rlratzel** 2023-06-24 20:03 UTC
