### ISSUE TITLE
[BUG]: ValueError: Unknown backend when setting 'backend_priority': 'cugraph'

### ISSUE THREAD

**Issue by wangxin52791** [rapidsai/cugraph#4341] opened 2024-04-12 06:32 UTC
### Version

nx-cugraph-cu11                          23.10.0

### Which installation method(s) does this occur on?

Source

### Describe the bug.

it  can be used in GPU，has no bugs

### Minimum reproducible example

```shell
os.environ['NETWORKX_AUTOMATIC_BACKENDS'] = 'cugraph'
bc = nx.betweenness_centrality(G,backend='cugraph')
```

### Relevant log output

```shell
File "/home/yifan/PatentNetML/inference/fast_api_sdf.py", line 3, in <module>
    import inference_bk
  File "/home/yifan/PatentNetML/inference/inference_bk.py", line 14, in <module>
    import network_case
  File "/home/yifan/PatentNetML/inference/network_case.py", line 8, in <module>
    import networkx as nx
  File "/home/yifan/.conda/envs/patentnetml/lib/python3.10/site-packages/networkx/__init__.py", line 19, in <module>
    from networkx import utils
  File "/home/yifan/.conda/envs/patentnetml/lib/python3.10/site-packages/networkx/utils/__init__.py", line 7, in <module>
    from networkx.utils.backends import *
  File "/home/yifan/.conda/envs/patentnetml/lib/python3.10/site-packages/networkx/utils/backends.py", line 265, in <module>
    config.backend_priority = [
  File "/home/yifan/.conda/envs/patentnetml/lib/python3.10/site-packages/networkx/utils/configs.py", line 97, in __setattr__
    self._check_config(key, value)
  File "/home/yifan/.conda/envs/patentnetml/lib/python3.10/site-packages/networkx/utils/configs.py", line 237, in _check_config
    raise ValueError(f"Unknown backend when setting {key!r}: {missing}")
ValueError: Unknown backend when setting 'backend_priority': 'cugraph'
Running on local URL:  http://127.0.0.1:7860
```

### Code of Conduct

- [X] I agree to follow cuGraph's Code of Conduct
- [X] I have searched the [open bugs](https://github.com/rapidsai/cugraph/issues?q=is%3Aopen+is%3Aissue+label%3Abug) and have found no duplicates for this bug report

**Comment by rlratzel** [comment] 2024-04-16 16:33
Hi @wangxin52791 , I was able to reproduce this bug by installing nx-cugraph 23.10 on the most recent networkx 3.3.  However, if I downgrade networkx to 3.2.1, or if I upgrade nx-cugraph to the latest 24.04, the bug is not present.  It would seem that this is a problem using an old version of nx-cugraph with the latest networkx.

Is it possible for you to upgrade nx-cugraph to the latest version 24.04?
cc @eriknw

**Comment by rlratzel** [comment] 2024-04-22 14:59
@wangxin52791 , I'm going to close this issue since it appears to be resolved when using the latest version of nx-cugraph.  Please re-open it or create a new issue if you're still having problems after upgrading.

**Closed by rlratzel** 2024-04-22 14:59 UTC
Labels: bug
