### ISSUE TITLE
[BUG] HITS analysis crashes

### ISSUE THREAD

**Issue by claudia-luca** [rapidsai/cugraph#1255] opened 2020-11-04 13:22 UTC
**Bug description**
I have a network of 500k nodes, 2mil edges. It's an undirected graph without self-loop.
When I run HITS() analysis it crashes.

**Code to reproduce bug**
```
# cuGraph depends on cuDF for data loading
gdf = cudf.from_pandas(edges)

def edges_to_cugraph(df, src_col, dst_col, drop_self_loops=False):
    
    # Drop self loop
    if drop_self_loops:
        df = df.copy(deep=False)
        df = df[ ~(df[src_col] == df[dst_col]) ]

    # Create list of nodes
    nodes_gdf = cudf.DataFrame({
        'id': cudf.concat([ df[src_col], df[dst_col] ], ignore_index=True, sort=False).unique()
    })
    nodes_gdf['idx'] = arange(0, len(nodes_gdf), dtype='int32')
    
    # Create cuGraph
    edges_gdf = df[[src_col, dst_col]]\
        .merge(
            nodes_gdf.rename(columns={'idx': 'src_idx'}, copy=False),
            left_on=src_col, right_on='id')\
        .merge(
            nodes_gdf.rename(columns={'idx': 'dst_idx'}, copy=False),
            left_on=dst_col, right_on='id')
    
    G = cugraph.Graph()
    G.from_cudf_edgelist(edges_gdf, source='src_idx', destination='dst_idx')
    
    return nodes_gdf, G

(nodes_gdf, G) = edges_to_cugraph(gdf, 'source', 'target', drop_self_loops=True); nodes_gdf.head()

%time ht = cugraph.hits(G); ht.head()
```

**Environment overview**
I'm using single GPU --> TITAN RTX - 24GB with the following configuration:
```
{'py': '3.7.8', 'graphistry: '0.14.0', 'pyarrow': '1.0.1', 'pandas': '1.1.4'}
rapids 0.16.0 cuda10.1_py37_gebb0e5c_85 rapidsai
```

**Error**
```
Degree Histogram (511793 vertices, 4763580 edges):
    Degree 0: 0 (0.000000 %)
    Degree 2^0: 6566 (1.282941 %)
    Degree 2^1: 68240 (13.333516 %)
    Degree 2^2: 216196 (42.242860 %)
    Degree 2^3: 160557 (31.371472 %)
    Degree 2^4: 47274 (9.236938 %)
    Degree 2^5: 10197 (1.992407 %)
    Degree 2^6: 2016 (0.393909 %)
    Degree 2^7: 668 (0.130522 %)
    Degree 2^8: 68 (0.013287 %)
    Degree 2^9: 11 (0.002149 %)
0	 0	 0	 queue3 	 oversize :	 3070758 ->	 4763582
0	 0	 0	 queue3 	 oversize :	 3070758 ->	 4763582
[/opt/conda/envs/rapids/conda-bld/libcugraph_1603309872808/work/cpp/build/cugunrock/src/cugunrock/gunrock/app/hits/hits_enactor.cuh, 135 @ gpu 0] cudaStreamSynchronize Failed (CUDA error 700: an illegal memory access was encountered)
[/opt/conda/envs/rapids/conda-bld/libcugraph_1603309872808/work/cpp/build/cugunrock/src/cugunrock/gunrock/app/enactor_base.cuh, 519 @ gpu 0] error encountered (CUDA error 700: an illegal memory access was encountered)
[/opt/conda/envs/rapids/conda-bld/libcugraph_1603309872808/work/cpp/build/cugunrock/src/cugunrock/gunrock/app/hits/hits_enactor.cuh, 387 @ gpu 0] error encountered (CUDA error 700: an illegal memory access was encountered)
[/opt/conda/envs/rapids/conda-bld/libcugraph_1603309872808/work/cpp/build/cugunrock/src/cugunrock/gunrock/util/array_utils.cuh, 835 @ gpu 0] hrank_curr cudaMemcpy D2H failed (CUDA error 700: an illegal memory access was encountered)
[/opt/conda/envs/rapids/conda-bld/libcugraph_1603309872808/work/cpp/build/cugunrock/src/cugunrock/gunrock/app/hits/hits_problem.cuh, 269 @ gpu 0] error encountered (CUDA error 700: an illegal memory access was encountered)
[/opt/conda/envs/rapids/conda-bld/libcugraph_1603309872808/work/cpp/build/cugunrock/src/cugunrock/gunrock/util/array_utils.cuh, 520 @ gpu 0] hits::frontier[0,0]::queues[0] cudaFree failed (CUDA error 700: an illegal memory access was encountered)
[/opt/conda/envs/rapids/conda-bld/libcugraph_1603309872808/work/cpp/build/cugunrock/src/cugunrock/gunrock/app/frontier.cuh, 185 @ gpu 0] error encountered (CUDA error 700: an illegal memory access was encountered)
[/opt/conda/envs/rapids/conda-bld/libcugraph_1603309872808/work/cpp/build/cugunrock/src/cugunrock/gunrock/app/enactor_types.cuh, 291 @ gpu 0] error encountered (CUDA error 700: an illegal memory access was encountered)
[/opt/conda/envs/rapids/conda-bld/libcugraph_1603309872808/work/cpp/build/cugunrock/src/cugunrock/gunrock/app/enactor_base.cuh, 250 @ gpu 0] error encountered (CUDA error 700: an illegal memory access was encountered)
[/opt/conda/envs/rapids/conda-bld/libcugraph_1603309872808/work/cpp/build/cugunrock/src/cugunrock/gunrock/app/hits/hits_enactor.cuh, 293 @ gpu 0] error encountered (CUDA error 700: an illegal memory access was encountered)
[/opt/conda/envs/rapids/conda-bld/libcugraph_1603309872808/work/cpp/build/cugunrock/src/cugunrock/gunrock/util/array_utils.cuh, 520 @ gpu 0] data_slices[0] cudaFree failed (CUDA error 700: an illegal memory access was encountered)
[/opt/conda/envs/rapids/conda-bld/libcugraph_1603309872808/work/cpp/build/cugunrock/src/cugunrock/gunrock/app/hits/hits_problem.cuh, 236 @ gpu 0] error encountered (CUDA error 700: an illegal memory access was encountered)
[/opt/conda/envs/rapids/conda-bld/libcugraph_1603309872808/work/cpp/build/cugunrock/src/cugunrock/gunrock/util/array_utils.cuh, 520 @ gpu 0] hrank_curr cudaFree failed (CUDA error 700: an illegal memory access was encountered)
[/opt/conda/envs/rapids/conda-bld/libcugraph_1603309872808/work/cpp/build/cugunrock/src/cugunrock/gunrock/app/hits/hits_problem.cuh, 117 @ gpu 0] error encountered (CUDA error 700: an illegal memory access was encountered)
[/opt/conda/envs/rapids/conda-bld/libcugraph_1603309872808/work/cpp/build/cugunrock/src/cugunrock/gunrock/util/array_utils.cuh, 520 @ gpu 0] data_slices[0] cudaFree failed (CUDA error 700: an illegal memory access was encountered)
[/opt/conda/envs/rapids/conda-bld/libcugraph_1603309872808/work/cpp/build/cugunrock/src/cugunrock/gunrock/app/hits/hits_problem.cuh, 236 @ gpu 0] error encountered (CUDA error 700: an illegal memory access was encountered)
[/opt/conda/envs/rapids/conda-bld/libcugraph_1603309872808/work/cpp/build/cugunrock/src/cugunrock/gunrock/util/array_utils.cuh, 520 @ gpu 0] row_offsets cudaFree failed (CUDA error 700: an illegal memory access was encountered)
[/opt/conda/envs/rapids/conda-bld/libcugraph_1603309872808/work/cpp/build/cugunrock/src/cugunrock/gunrock/graph/csr.cuh, 108 @ gpu 0] error encountered (CUDA error 700: an illegal memory access was encountered)
[/opt/conda/envs/rapids/conda-bld/libcugraph_1603309872808/work/cpp/build/cugunrock/src/cugunrock/gunrock/app/app_base.cuh, 134 @ gpu 0] error encountered (CUDA error 700: an illegal memory access was encountered)
```

**Comment by ChuckHastings** [comment] 2021-02-05 16:40
I am unable to reproduce your error using the latest 0.18 version (soon to be released).  I tested with the Hollywood data set which is a bit larger than yours (1 million vertices, 113 million edges) and successful results.

I had a question regarding your code in `edges_to_cugraph`.  You appear to be attempting to renumber your vertices prior to calling `from_cudf_edgelist` to populate the graph.  This is not actually a necessary step in cuGraph anymore.  `from_cudf_edgelist` will automatically renumber your data into the range [0, number_of_unique_vertices), and if you let cuGraph do that then all of your results will be presented using your original vertex ids.  The renumbering is currently implemented in a similar manner to what you are doing, but work is planned for a future release to create an optimized version.  So moving toward letting `from_cudf_edgelist` handle the renumbering for you will ultimately lead to a more optimized solution (and less work for you).

I would suggest trying your data set against release 0.18 (either the current nightly build or wait until the formal release comes out in a few weeks) and updating this issue.  If your data set is still failing with the latest code then we might need to investigate a bit more around what exactly in your data is causing the error.

**Closed** 2021-02-09 16:18 UTC
Labels: bug
