### ISSUE TITLE
[BUG]:Import Error when trying to run cugraph benchmark on single GPU

### ISSUE THREAD

**Issue by Daramfon10** [rapidsai/cugraph#3321] opened 2023-03-08 14:33 UTC
### Version

23.04

### Describe the bug.

The error seen is **"E   ImportError: cannot import name 'raft_include_test' from 'raft_dask'"**. This happens when I go through the documentation to build and then run the benchmarks by running pytest -v. 

Build - https://github.com/rapidsai/cugraph/blob/branch-23.04/readme_pages/SOURCEBUILD.md
Run benchmarks - https://github.com/rapidsai/cugraph/tree/branch-23.04/benchmarks/cugraph/pytest-based

### Minimum reproducible example

```shell
1. Build from source.
2. cd into benchmarks and run pytest -v
```

### Relevant log output

```shell
============================================================== ERRORS ===============================================================_______________________________________ ERROR collecting cugraph/pytest-based/bench_algos.py ________________________________________ImportError while importing test module '/mnt/resource_nvme/cugraph/benchmarks/cugraph/pytest-based/bench_algos.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../../../anaconda3/envs/cugraph_dev/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
bench_algos.py:32: in <module>
    import cugraph
../../../../anaconda3/envs/cugraph_dev/lib/python3.10/site-packages/cugraph/__init__.py:107: in <module>
    from raft_dask import raft_include_test
E   ImportError: cannot import name 'raft_include_test' from 'raft_dask' (/mnt/resource_nvme/anaconda3/envs/cugraph_dev/lib/python3.10/site-packages/raft_dask/__init__.py)
__________________________ ERROR collecting cugraph/pytest-based/bench_cugraph_uniform_neighbor_sample.py ___________________________ImportError while importing test module '/mnt/resource_nvme/cugraph/benchmarks/cugraph/pytest-based/bench_cugraph_uniform_neighbor_sample.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../../../anaconda3/envs/cugraph_dev/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
bench_cugraph_uniform_neighbor_sample.py:20: in <module>
    from cugraph.testing.mg_utils import start_dask_client, stop_dask_client
../../../../anaconda3/envs/cugraph_dev/lib/python3.10/site-packages/cugraph/__init__.py:107: in <module>
    from raft_dask import raft_include_test
E   ImportError: cannot import name 'raft_include_test' from 'raft_dask' (/mnt/resource_nvme/anaconda3/envs/cugraph_dev/lib/python3.10/site-packages/raft_dask/__init__.py)
====================================================== short test summary info ======================================================ERROR bench_algos.py
ERROR bench_cugraph_uniform_neighbor_sample.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 2 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!========================================================= 2 errors in 6.96s =========================================================
```

### Code of Conduct

- [X] I agree to follow cuGraph's Code of Conduct
- [X] I have searched the [open bugs](https://github.com/rapidsai/cugraph/issues?q=is%3Aopen+is%3Aissue+label%3Abug) and have found no duplicates for this bug report

**Comment by rlratzel** [comment] 2023-03-08 19:38
[This PR](https://github.com/rapidsai/cugraph/pull/3306) was recently merged and should fix this problem.  Can you use the latest cugraph (either the tip of `branch-23.04` if building from source, or the latest cugraph conda install from `rapidsai-nightly`) and verify the problem is resolved for you?

**Comment by Daramfon10** [comment] 2023-03-09 19:44
Hello @BradReesWork - Thanks for the guidance. I was able to run the benchmark but I have a lot of interesting errors, especially a lot of **"FileNotFoundError: /mnt/resource_nvme/anaconda3/envs/cugraph_dev/lib/python3.10/site-packages/cugraph/testing/../datasets/csv/directed/cit-Patents.csv could not be resolved to any files"**

I have attached the log file for your reference. 

[cugraph_output2.log](https://github.com/rapidsai/cugraph/files/10935443/cugraph_output2.log)

**Comment by kingmesal** [comment] 2023-03-24 19:12
@rlratzel any updates?

**Closed** 2023-04-24 17:33 UTC
Labels: bug
