### ISSUE TITLE
[DOC]: Create an MG notebook on centrality/similarity

### ISSUE THREAD

**Issue by acostadon** [rapidsai/cugraph#3015] opened 2022-12-01 12:53 UTC
### How would you describe the priority of this documentation request

High

### Describe the future/missing documentation

Customer has asked for a notebook to demonstrate centrality and similarty algorithms on Multi-GPU 

### Where have you looked?

https://github.com/rapidsai/cugraph/tree/branch-23.02/notebooks/algorithms
https://github.com/rapidsai/cugraph/tree/branch-23.02/notebooks/demo

### Code of Conduct

- [X] I agree to follow cuGraph's Code of Conduct
- [X] I have searched the [open documentation issues](https://github.com/rapidsai/cugraph/issues?q=is%3Aopen+is%3Aissue+label%3Adoc) and have found no duplicates for this bug report

**Comment by BradReesWork** [comment] 2023-01-04 14:11
duplicate of #2669

**Closed by BradReesWork** 2023-01-04 14:11 UTC
Labels: feature request, doc, P0
