### ISSUE TITLE
[FEA] Performance regression tests

### ISSUE THREAD

**Issue by afender** [rapidsai/cugraph#209] opened 2019-04-04 21:32 UTC
We need to identify when a change in the repo results in a significant performance drop.

**Task List**
- [x] record the time on the largest python dataset for each algorithm
- [x] work with Ops team to enable a way to compare these times to reference times

**Comment by afender** [comment] 2020-04-27 19:13
The core part is there thanks to the work @rlratzel did with the ASV portal.
@rlratzel and @BradReesWork, let's find some time to sync up on reporting and process so that developers can leverage this.

**Comment by rlratzel** [comment] 2020-05-27 23:26
Closing this since the new benchmarks (described [here](https://github.com/rapidsai/cugraph/blob/branch-0.14/benchmarks/README.md)) allow for manual discovery of performance regressions.  These are run nightly, and generate reports that can be viewed [here](http://10.33.227.188:88/asv/cugraph-e2e/html/#/summarylist)

A future update may leverage the new benchmark code to also perform a CI-style check, where a regression that's too large may block a merge.  This approach could also be taken for nightly runs, where a failure notification would be generated (as opposed to blocking a merge).

**Closed by rlratzel** 2020-05-27 23:26 UTC
Labels: feature request
