### ISSUE TITLE
[BUG] Extract tests to a folder within the repository and remove hardcoded dataset paths

### ISSUE THREAD

**Issue by dillon-cullinan** [rapidsai/cugraph#171] opened 2019-03-21 16:11 UTC
**Describe the bug**
Currently, cuGraphs tests are being extracted into the root directory. This is bad for the end user if they decide to run the optional tests, not all users have those permissions on their machines.

Also, within the python tests, there are many hardcoded paths to the `/datasets/` directory which is assumed to exist. This is currently being worked around in CI but it should be fixed within the repository itself.

**To Reproduce**
From a blank machine, following the source code steps in the README.md will result in possible Permissions errors or file/folder not found errors when running tests for cuGraph.

**Expected behavior**
Tests should be extracted into a new folder within the repo. Datasets should follow suit.

**Screenshots**
gpuCI output:

```22:34:26 >>>> Python py.test for cuGraph...
22:34:26 
22:34:26 ./datasets/
22:34:26 ./datasets/golden_data/
22:34:26 ./datasets/golden_data/graphs/
22:34:26 ./datasets/golden_data/graphs/dblp.mtx
22:34:26 ./datasets/networks/
22:34:26 tar: ./datasets/golden_data/graphs/dblp.mtx: Cannot open: File exists
22:34:26 tar: ./datasets/golden_data/graphs: Cannot utime: Read-only file system
22:34:26 tar: ./datasets/golden_data: Cannot utime: Read-only file system
22:34:26 ./datasets/networks/polbooks.mtx
22:34:26 tar: ./datasets/networks/polbooks.mtx: Cannot open: File exists
22:34:26 tar: ./datasets/networks/netscience.mtx: Cannot open: File exists
22:34:26 tar: ./datasets/networks/dolphins.mtx: Cannot open: File exists
22:34:26 tar: ./datasets/networks/karate.mtx: Cannot open: File exists
22:34:26 tar: ./datasets/networks: Cannot utime: Read-only file system
22:34:26 tar: ./datasets: Cannot utime: Read-only file system
22:34:26 tar: Exiting with failure status due to previous errors
22:34:26 ./datasets/networks/netscience.mtx
22:34:26 ./datasets/networks/dolphins.mtx
22:34:26 ./datasets/networks/karate.mtx
22:34:27 Build step 'Execute shell' marked build as failure
22:34:28 Recording test results```

**Comment by afender** [comment] 2019-03-21 16:52
Duplicate of #79 and #156.

I think we need a single policy across RAPIDS for where the test data should be and how it should be provided to tests. @rlratzel do we have that at this point?

The `/dadaset` approach is something that was recommended to us a few months back. We can definitely change that but I'd like to avoid re-doing this again later on.

**Comment by afender** [comment] 2019-03-21 16:57
Also, the `.tar` file inside the repo is a hack that cannot scale as we add datasets. We need a proper way to deploy test data too.

**Comment by rlratzel** [comment] 2019-03-21 17:23
We do not have a policy for how test data is deployed/generated/made available/cleaned up/etc., but I agree that we should have a RAPIDS-wide solution. I'll work with others on a proposal and submit it for review.

**Comment by rlratzel** [comment] 2019-04-11 20:28
This is now closed, relevant PRs:
#203 
#211 
#215

**Closed by rlratzel** 2019-04-11 20:28 UTC
Labels: bug, duplicate
