### ISSUE TITLE
Research spike for scoping sampling behavior alignment b/w dgl and pyg

### ISSUE THREAD

**Issue by kingmesal** [rapidsai/cugraph#3444] opened 2023-04-06 17:13 UTC
* requirement from cugraph-ops team
* there's a difference between cugraph and DGL sampling - need to align
* include research on COO->CSR/C conversion

```[tasklist]
### Tasks
- [ ] Add a draft title or issue reference here
```

**Comment by rlratzel** [comment] 2023-05-23 21:07
duplicate of #3423

**Closed by rlratzel** 2023-05-23 21:07 UTC
Labels: Story
