### ISSUE TITLE
Nightly Benchmarks for Bulk Sampling (PyG), Feature Fetching (PyG), and MFG Creation (PyG)

### ISSUE THREAD

**Issue by alexbarghi-nv** [rapidsai/cugraph#3637] opened 2023-06-05 16:04 UTC
Add benchmarks for these 3 operations that will be run nightly.

Verification criteria:
1. Benchmarks are merged into cuGraph repository
2. Benchmarks successfully run nightly and report their results somewhere

**Comment by BradReesWork** [comment] 2023-08-17 19:35
blocked - code is being refactored, waiting for that before this issue

**Comment by kingmesal** [comment] 2023-08-21 20:42
If this is not unblocked by Sep. 8th, it will need to be prioritized for the following release.

**Comment by rlratzel** [comment] 2023-11-01 16:28
closing as a duplicate of rapidsai/graph_dl#177

**Closed by rlratzel** 2023-11-01 16:28 UTC
Labels: Story
