### ISSUE TITLE
How to read the graph edge if the node value is non-numerical

### ISSUE THREAD

**Issue by han-jiang-etsy** [rapidsai/cugraph#2686] opened 2022-09-12 16:37 UTC
Hi team, I am exploring the cugraph, and the base image is `rapidsai/rapidsai:cuda11.0-base-ubuntu20.04-py3.8`. 

I have tested on the input with node value being numerical, and it worked fine. But it failed when the input become a string. the error occured inside `dcg.pagerank(G_dask, tol=1e-4)`

```
import time
import cudf
import cugraph
import cugraph.dask as dcg
import dask_cudf
import pandas as pd
from cugraph.dask.comms import comms as Comms
from dask.distributed import Client, wait
from dask_cuda import LocalCUDACluster


def setup():
    cluster = LocalCUDACluster(threads_per_worker=1)
    client = Client(cluster)
    Comms.initialize(p2p=True)
    return (client, cluster)


def teardown(client, cluster=None):
    Comms.destroy()
    client.close()
    if cluster:
        cluster.close()

if __name__ == "__main__":

    # setting up the cluster
    setup_objs = setup()

    # dummy data
    df = pd.DataFrame(
        {
            "src": ['a1', 'a1', 'a2', 'a3'],
            "dst": ['a2', 'a3', 'a4', 'a4'],
        }
    )
    input_file = "dummy.csv"
    df.to_csv(input_file, index=False, header=False, sep="\t")

    chunksize = dcg.get_chunksize(input_file)
    e_list = dask_cudf.read_csv(
        input_file, chunksize=chunksize, delimiter="\t", names=["src", "dst"], dtype=[str, str]
    )

    G_dask = cugraph.DiGraph()
    G_dask.from_dask_cudf_edgelist(e_list, source="src", destination="dst")
    pr_df = dcg.pagerank(G_dask, tol=1e-4)
    logger.info(f"print out {pr_df.head(4)}")

    # tearing fown the cluster
    teardown(*setup_objs)
```

**Comment by han-jiang-etsy** [comment] 2022-09-12 16:47
the full error message 

2022-09-12 16:46:01,043 - distributed.preloading - INFO - Import preload module: dask_cuda.initialize
/opt/conda/envs/rapids-22.06/lib/python3.8/site-packages/cudf/core/dataframe.py:1055: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  return pd.Series(self._dtypes)
/opt/conda/envs/rapids-22.06/lib/python3.8/site-packages/cudf/core/dataframe.py:1055: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  return pd.Series(self._dtypes)
/opt/conda/envs/rapids-22.06/lib/python3.8/site-packages/cudf/core/dataframe.py:1055: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  return pd.Series(self._dtypes)
/opt/conda/envs/rapids-22.06/lib/python3.8/site-packages/cudf/core/dataframe.py:1055: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  return pd.Series(self._dtypes)
/opt/conda/envs/rapids-22.06/lib/python3.8/site-packages/cudf/core/join/_join_helpers.py:111: UserWarning: Can't safely cast column from int64 to object, upcasting to None.
  warnings.warn(
Traceback (most recent call last):
  File "cugraph_test_mp.py", line 43, in <module>
    pr_df = dcg.pagerank(G_dask, tol=1e-4)
  File "/opt/conda/envs/rapids-22.06/lib/python3.8/site-packages/cugraph/dask/link_analysis/pagerank.py", line 143, in pagerank
    input_graph.compute_renumber_edge_list(transposed=True)
  File "/opt/conda/envs/rapids-22.06/lib/python3.8/site-packages/cugraph/structure/graph_implementation/simpleDistributedGraph.py", line 524, in compute_renumber_edge_list
    NumberMap.renumber_and_segment(
  File "/opt/conda/envs/rapids-22.06/lib/python3.8/site-packages/cugraph/structure/number_map.py", line 642, in renumber_and_segment
    renumber_map.implementation.ddf = indirection_map.merge(
  File "/opt/conda/envs/rapids-22.06/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/opt/conda/envs/rapids-22.06/lib/python3.8/site-packages/dask_cudf/core.py", line 145, in merge
    return super().merge(other, on=on, shuffle="tasks", **kwargs)
  File "/opt/conda/envs/rapids-22.06/lib/python3.8/site-packages/dask/dataframe/core.py", line 5191, in merge
    return merge(
  File "/opt/conda/envs/rapids-22.06/lib/python3.8/site-packages/dask/dataframe/multi.py", line 584, in merge
    return single_partition_join(
  File "/opt/conda/envs/rapids-22.06/lib/python3.8/site-packages/dask/dataframe/multi.py", line 399, in single_partition_join
    meta = left._meta_nonempty.merge(right._meta_nonempty, **kwargs)
  File "/opt/conda/envs/rapids-22.06/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/opt/conda/envs/rapids-22.06/lib/python3.8/site-packages/cudf/core/dataframe.py", line 3474, in merge
    gdf_result = super()._merge(
  File "/opt/conda/envs/rapids-22.06/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/opt/conda/envs/rapids-22.06/lib/python3.8/site-packages/cudf/core/frame.py", line 2278, in _merge
    return merge_cls(
  File "/opt/conda/envs/rapids-22.06/lib/python3.8/site-packages/cudf/core/join/join.py", line 186, in perform_merge
    lcol_casted, rcol_casted = _match_join_keys(lcol, rcol, self.how)
  File "/opt/conda/envs/rapids-22.06/lib/python3.8/site-packages/cudf/core/join/_join_helpers.py", line 116, in _match_join_keys
    return lcol.astype(common_type), rcol.astype(common_type)
  File "/opt/conda/envs/rapids-22.06/lib/python3.8/site-packages/cudf/core/column/column.py", line 891, in astype
    return self.as_numerical_column(dtype, **kwargs)
  File "/opt/conda/envs/rapids-22.06/lib/python3.8/site-packages/cudf/core/column/string.py", line 5239, in as_numerical_column
    raise ValueError(
ValueError: Could not convert strings to float type due to presence of non-floating values.
Exception ignored in: <function Comms.__del__ at 0x7f3ada37b550>
Traceback (most recent call last):
  File "/opt/conda/envs/rapids-22.06/lib/python3.8/site-packages/raft/dask/common/comms.py", line 134, in __del__
  File "/opt/conda/envs/rapids-22.06/lib/python3.8/site-packages/raft/dask/common/comms.py", line 226, in destroy
  File "/opt/conda/envs/rapids-22.06/lib/python3.8/site-packages/distributed/client.py", line 2793, in run
  File "/opt/conda/envs/rapids-22.06/lib/python3.8/site-packages/distributed/utils.py", line 320, in sync
  File "/opt/conda/envs/rapids-22.06/lib/python3.8/site-packages/distributed/utils.py", line 377, in sync
  File "/opt/conda/envs/rapids-22.06/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 222, in add_callback
AttributeError: 'NoneType' object has no attribute 'get_ident'

**Comment by BradReesWork** [comment] 2022-09-12 18:02
@han-jiang-etsy 

It looks like you have uncovered a small bug

The code works for single GPU but not multi-GPU (dask).  We will get this addressed

`
e_list_gdf = cudf.read_csv(input_file, delimiter="\t", names=["src", "dst"], dtype=['str', 'str'])
G = cugraph.Graph(directed=True)
G.from_cudf_edgelist(e_list_gdf, source="src", destination="dst")
pr_df = cugraph.pagerank(G, tol=1e-4)

`

**Comment by han-jiang-etsy** [comment] 2022-09-12 19:27
@BradReesWork thank you. Is there a workaround by creating mapping from vertex ID to numerical ID in the dataframe upfront, so the graph can still process it and and map it back in the output dataframe to vertex ID

**Comment by rlratzel** [comment] 2022-09-13 04:14
Hello @han-jiang-etsy , I was able to use your example to reproduce the failure in my dev environment and fix the problem.  I also created a new unit test and added it to our multi-GPU (dask) test suite based on your example, which you can see [here](https://github.com/rapidsai/cugraph/blob/dbf31a2548839f10cf92029b6190638c5524a022/python/cugraph/cugraph/tests/mg/test_mg_renumber.py#L297) in PR #2688 .

After #2688 passes CI, is approved, then merged, you should be able to use a nightly build of cugraph from our `rapidsai-nightly` conda channel [here](https://anaconda.org/rapidsai-nightly/cugraph), or just pull the latest sources from the cugraph `branch-22.10` branch and build/install from source.

Lastly, when #2688 is merged, it will auto-close this issue. If you still have problems with string vertex IDs or any other aspect of this issue after installing the latest version of cugraph, please re-open it and let us know.

**Comment by han-jiang-etsy** [comment] 2022-09-13 13:54
@rlratzel the test looks good. Thanks for the prompt response. I know we have only tested on page rank, but I can see the PR is a general fix so it applies for any algorithm, is my assumption correct.

**Comment by rlratzel** [comment] 2022-09-13 16:08
> @rlratzel the test looks good. Thanks for the prompt response. I know we have only tested on page rank, but I can see the PR is a general fix so it applies for any algorithm, is my assumption correct.

Yes, the fix was to the code responsible for the vertex ID renumbering (which also applies to string vertex IDs) that affects all algorithms.  The renumbering step converts vertex IDs in the input (strings, non-contiguous ints, etc.) into a contiguous series of integers starting from zero, which is what the algos then use. So ideally if this works for one algo it should work for the others.  

However, now that you've mentioned it, I just submitted [this issue](https://github.com/rapidsai/cugraph/issues/2691) to add more testing for string vertex IDs to other algos to cover any potential special cases not covered by testing renumbering alone.

**Comment by han-jiang-etsy** [comment] 2022-09-13 18:07
@rlratzel really appreciate the team's efforts to maintain the high quality of the code

**Closed** 2022-09-23 17:37 UTC
Labels: bug, question
