### ISSUE TITLE
[BUG] gtests/PAGERANK_TEST and gtests/SSSP_TEST fail

### ISSUE THREAD

**Issue by seunghwak** [rapidsai/cugraph#78] opened 2019-02-15 22:39 UTC
**gtests/PAGERANK_TEST**
_segmentation fault (core dumped)_

**gtests/SSSP_TEST**
SSSP_TEST
home/seunghwak/RAPIDS/cugraph/cpp/src/tests/nvgraph_plugin/nvgraph_gdf_sssp.cpp:182: Failure
Value of: fpin != NULL
Actual: false
Expected: true
_Cannot read file with reference data: /datasets/golden_data/results/sssp/dblp_T.sssp_100000.bin_

[  FAILED  ] golden_test/Tests_Sssp2.CheckFP32_manualT/1, where GetParam() = 72-byte object <B0-6C 33-46 2E-56 00-00 25-00 00-00 00-00 00-00 25-00 00-00 00-00 00-00 73-75 6C-74 73-2F 73-73 E0-6D 33-46 2E-56 00-00 39-00 00-00 00-00 00-00 39-00 00-00 00-00 00-00 6E-00 00-00 00-00 00-00 A0-86 01-00 00-00 00-00> (229 ms)
[ RUN      ] golden_test/Tests_Sssp2.CheckFP32_manualT/2
0.899,0.178,2.248,0.296
/home/seunghwak/RAPIDS/cugraph/cpp/src/tests/nvgraph_plugin/nvgraph_gdf_sssp.cpp:182: Failure
Value of: fpin != NULL
Actual: false
Expected: true
Cannot read file with reference data: /datasets/golden_data/results/sssp/dblp_T.sssp_100.bin

[  FAILED  ] golden_test/Tests_Sssp2.CheckFP32_manualT/2, where GetParam() = 72-byte object <B0-6C 33-46 2E-56 00-00 25-00 00-00 00-00 00-00 25-00 00-00 00-00 00-00 73-75 6C-74 73-2F 73-73 30-69 33-46 2E-56 00-00 36-00 00-00 00-00 00-00 36-00 00-00 00-00 00-00 6E-00 00-00 00-00 00-00 64-00 00-00 00-00 00-00> (225 ms)
[ RUN      ] golden_test/Tests_Sssp2.CheckFP32_manualT/3
_Segmentation fault (core dumped)_

**Comment by afender** [comment] 2019-02-15 22:48
You are missing C++ tests datasets.
Closing as duplicate of #65

**Closed by afender** 2019-02-15 22:48 UTC
Labels: duplicate
