### ISSUE TITLE
BLOG on GNN Scaling

### ISSUE THREAD

**Issue by BradReesWork** [rapidsai/cugraph#3365] opened 2023-03-24 17:11 UTC
### How would you describe the priority of this documentation request

Medium

### Describe the future/missing documentation

Create a BLOG showing how cugraph-pyg/cugraph-dgl scales.   Also include scaling numbers for DGL/PyG 

### Where have you looked?

N/A

### Code of Conduct

- [X] I agree to follow cuGraph's Code of Conduct
- [X] I have searched the [open documentation issues](https://github.com/rapidsai/cugraph/issues?q=is%3Aopen+is%3Aissue+label%3Adoc) and have found no duplicates for this bug report

**Comment by rlratzel** [comment] 2023-05-19 16:56
duplicate of #3437

**Closed by rlratzel** 2023-05-19 16:56 UTC
Labels: doc, Story
