### ISSUE TITLE
Intermittent, irreproducable, exception raised running SSSP in cuGraph when there doesn't appear to be an error [BUG]

### ISSUE THREAD

**Issue by MurrayData** [rapidsai/cugraph#342] opened 2019-06-21 05:51 UTC
**Describe the bug**

Sorry folks, I know from experience that intermittent, irreproducable, errors are some of the hardest to investigate.

I am getting an intermittent error when running cuGraph SSSP which doesn't appear to be an error as CUDA is reporting success, yet it raises an exception.

This makes me wonder if cuGraph is detecting an error when there isn't one and the problem relates to checking the return code?

```
---------------------------------------------------------------------------
GDFError                                  Traceback (most recent call last)
<timed exec> in <module>

cugraph/sssp/sssp_wrapper.pyx in cugraph.sssp()

cugraph/sssp/sssp_wrapper.pyx in cugraph.sssp()

cudf/bindings/cudf_cpp.pyx in cudf.bindings.cudf_cpp.check_gdf_error()

cudf/bindings/cudf_cpp.pyx in cudf.bindings.cudf_cpp.check_gdf_error()

GDFError: CUDA ERROR. b'cudaSuccess': b'no error'
```

I was running 2.5 million SSSP requests, chunked in batches of 1000, against a list of GB postcodes. Out of 2.5 million, this error occurred 4 times.

```
%%time
start = 1335000
end = 1500000
inc = 1000

for n in range(start,end,inc):
    store_drivetimes = []
    last = min(len(stores[0]),n+inc)
    # for each store 
    for i in range(n,last):
        query_x = "((x1>="+str(stores[1][i]-1000)+" and x1<="+str(stores[1][i]+1000)+") or (x2>="+str(stores[1][i]-1000)+" and x2<="+str(stores[1][i]+1000)+"))"
        query_y = "((y1>="+str(stores[2][i]-1000)+" and y1<="+str(stores[2][i]+1000)+") or (y2>="+str(stores[2][i]-1000)+" and y2<="+str(stores[2][i]+1000)+"))"
        qdf = gdf.query("("+query_x+" and "+query_y+")")
        #print(qdf.to_pandas())
        # create a road Graph weighted on lenght of edge
        G = cugraph.Graph()
        G.add_edge_list(qdf["src_0"], qdf["dst_0"],qdf['length'])
        # Call cugraph.sssp to get the drivetime from store vertex
        df = cugraph.sssp(G,stores[0][i])
        # Filter 1km and save results
        store_drivetimes += [df.query("distance<=1000")]

    # output into single csv with store id as label
    outfile='/data/drive_times/spatia_paths_'+str(n)+'_'+str(last)+'.csv'
    f = open(outfile, 'w')
    f.close()

    for i,d in enumerate(store_drivetimes):
        labels = np.ones(d['vertex'].count(),dtype=np.int) * stores[0][i]
        with open(outfile, 'a') as f:
            d.to_pandas().assign(store=labels).to_csv(f, index=False, header=True if i==0 else False, sep=',')
        if i+1 % 1000 == 0:
            print("Output",i+1)

    print("Output",n,len(store_drivetimes))
```

**To Reproduce**

I am unable to reproduce as the problem is intermittent and infrequent (4 in 2.5 million).

If re-run the code executes normally.

I created a stress testing scenario on various GPUs and the problem occurs on Titan V, Titan Xp, Titan RTX and GTX 1080, so is not related to underlying GPU architecture, but it is entirely random and runs successfully when restarted, I did not get the error on GV100 GPUs in 2 million attempts.

Frequency of occurrence is approximately 1 in 600K runs.

The memory usage is well within the amount available.

**Expected behavior**

Normal Completion

**Screenshots**

![image](https://user-images.githubusercontent.com/8914493/59899823-15dfd180-93ee-11e9-86bd-90c191886d3c.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 LTS
 - CUDA 10.1
 - Chrome Version 74.0.3729.169 (Official Build) (64-bit)
 - NVIDIA Docker 2

Docker container (unmodified) runtime 0.7 CUDA 10.0 Ubuntu 18.04
Method of cuDF install: Docker
```
docker pull rapidsai/rapidsai:0.7-cuda10.0-runtime-ubuntu18.04-gcc7-py3.7
docker run --runtime=nvidia  --name rapids0.7 --rm -it -p 8888:8888 -p 8787:8787 -p 8786:8786   -v /home/john/Data/
```

**Comment by pgera** [comment] 2019-06-21 21:14
@MurrayData , we changed the underlying SSSP implementation in the 0.8 branch to a different one. So it would be really helpful to know if this still reproduces on the 0.8 branch (or after the 0.8 release).

**Comment by MurrayData** [comment] 2019-06-22 05:59
Thanks @pgera. I will create a stress testing scenario on 0.8.

**Comment by MurrayData** [comment] 2019-06-22 06:11
Thank you @pgera. I've just downloaded this version of the nightly container:
```
docker pull rapidsai/rapidsai-nightly:0.8-cuda10.0-runtime-ubuntu18.04-gcc7-py3.7
```
I'm out this weekend, but I'll leave it running in a stress test scenario and let you know what happens. I'll also check how the results compare with 0.7.

**Comment by pgera** [comment] 2019-06-22 06:30
From a quick look at docker hub, it looks like that tag is 10 days old. The new implementation was merged yesterday. So I don't think that docker container has the latest changes.

**Comment by MurrayData** [comment] 2019-07-04 06:29
@pgera I have been unable to recreate the situation in the latest 0.8 release despite exhaustive testing.

**Comment by pgera** [comment] 2019-07-04 06:43
Great. Did you see any performance differences in the 0.8 release ? It should, hopefully, be faster. Also, the new 'unreachable' API filters out nodes with infinite distances.

**Comment by MurrayData** [comment] 2019-07-04 07:12
Yes @pgera, huge improvements. I re-ran the UK road graph searches and they are 2.5-3x faster than before. The filter is great too as it permits queries and the predecessor node is a huge bonus. I tweeted about it.

**Comment by afender** [comment] 2019-07-19 21:40
Excellent! Closing this issue since it does not repro with the new SSSP.

**Closed by afender** 2019-07-19 21:40 UTC
Labels: ? - Needs Triage, bug
