### ISSUE TITLE
Docs not building correctly

### ISSUE THREAD

**Issue by vmjersey** [rapidsai/cugraph#1502] opened 2021-04-01 18:26 UTC
Steps to reproduce:
git clone https://github.com/rapidsai/cugraph.git
cd cugraph
git checkout branch-0.18   # although branch doesn't seem to make a difference
cd docs
pip install -r requirement.txt  
make html
...
WARNING: autodoc: failed to import module 'link_prediction.woverlap' from module 'cugraph'; the following exception was raised:
cannot import name 'louvain_wrapper' from 'cugraph.community' (/home/jlbark/cugraph/python/cugraph/community/__init__.py)
WARNING: autodoc: failed to import module 'traversal.bfs' from module 'cugraph'; the following exception was raised:
cannot import name 'louvain_wrapper' from 'cugraph.community' (/home/jlbark/cugraph/python/cugraph/community/__init__.py)
WARNING: autodoc: failed to import module 'traversal.sssp' from module 'cugraph'; the following exception was raised:
cannot import name 'louvain_wrapper' from 'cugraph.community' (/home/jlbark/cugraph/python/cugraph/community/__init__.py)
...
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] nx_transition                                                                                                                                      
generating indices...  genindexdone
writing additional pages...  searchdone
copying images... [100%] ./images/Nx_Cg_2.png                                                                                                                               
copying static files... ... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded, 34 warnings.

The HTML pages are in build/html.
cp -r source/images build/html

there are files in build/html, but the api documentation doesn't get rendered.

Anaconda Version: 2020.11
OS:  RHEL 7.9

**Comment by BradReesWork** [comment] 2021-04-01 20:00
@vmjersey thanks for posting the issue.  I'm looking into it

**Comment by rlratzel** [comment] 2021-04-03 01:23
@vmjersey, I think the warnings you saw were related to `ImportError`s that need to be resolved before the docs can be properly generated.

I see the same behavior you described when I try to build docs without having built cugraph first.  Did you build `cugraph` (described [here](https://github.com/rapidsai/cugraph/blob/branch-0.19/SOURCEBUILD.md)) before attempting to build the docs, and if so, did it build successfully are are you able to `import cugraph` in Python without error?

Regardless, I'll update the `README.md` to mention that cugraph must be built as a prerequisite to building docs.

**Comment by rlratzel** [comment] 2021-04-03 01:31
Also, in the root of the cugraph source dir is the `build.sh` script which you may have read about in the link above describing how to build from source.  I recommend running that script to build cugraph since it not only builds the libraries but also builds the docs afterwards by default.  This might be the easiest way to get everything built, including docs.

**Comment by vmjersey** [comment] 2021-04-03 03:25
So cugraph built sucessfully and I was able to import cugraph in python.   I even tried to import the classes from specific warnings that spat out.

**Comment by rlratzel** [comment] 2021-04-05 06:03
I suspect that the problem may still be related to the warnings (plus, you shouldn't be getting them anyway) and that sphinx's environment may be different than the one which you're able to successfully `import cugraph` from.  I have a couple of suggestions:

1) edit the `Makefile` in the `docs` dir to change the line starting with `SPHINXOPTS` to:
```
SPHINXOPTS    = -W
```
This will treat warnings as errors so sphinx will fail faster and allow you to examine one warning at a time instead of looking through several.

2) Try the following from a python prompt started in the `docs/source` dir:
```
(rapids) root@791d64d08dd0:/rapids/cugraph/docs/source# python -i conf.py
>>> import cugraph
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/rapids/cugraph/python/cugraph/__init__.py", line 14, in <module>
    from cugraph.community import (
  File "/rapids/cugraph/python/cugraph/community/__init__.py", line 14, in <module>
    from cugraph.community.louvain import louvain
  File "/rapids/cugraph/python/cugraph/community/louvain.py", line 14, in <module>
    from cugraph.community import louvain_wrapper
ImportError: cannot import name 'louvain_wrapper' from partially initialized module 'cugraph.community' (most likely due to a circular import) (/rapids/cugraph/python/cugraph/community/__init__.py)
>>>
```
This should reproduce the steps taken by sphinx when it attempts to `import cugraph` to generate docs. In the above example, I ran `python -i conf.py` from the `docs/source` dir and then interactively attempted to `import cugraph` before having built it to demonstrate an `ImportError`.  Sphinx loads `conf.py` during doc generation, so this should allow you to reproduce the environment sphinx uses when the warnings are shown to hopefully display a complete traceback that could assist in debugging the source of the warnings.

**Comment by rlratzel** [comment] 2021-04-09 03:14
@vmjersey did you have any luck with the above suggestions?

**Comment by rlratzel** [comment] 2021-04-16 19:25
closing this, but please re-open or file another issue if the problem persists.

**Closed by rlratzel** 2021-04-16 19:25 UTC
Labels: bug, doc

**Comment by vmjersey** [comment] 2021-04-20 15:26
Sorry it took me so long to get back to this.  I was able to actually get it to build.  I think the reason this failed for me was that I deleted my build directory after installing it and that is what was giving the documentation build all the issues.
