### ISSUE TITLE
[BUG] is_edge_ids in uniform_sampling does not seem to do anything

### ISSUE THREAD

**Issue by VibhuJawa** [rapidsai/cugraph#2562] opened 2022-08-10 22:12 UTC
**Describe the bug**

When we pass `is_edge_ids=True` we dont seem to do anything with it in the ` uniform_neighbor_sample` function (see below).   We should triage this and fix it accordingly. 

https://github.com/rapidsai/cugraph/blob/7d8f0fd63ad58ce6deada5508bfc08ee9aa46d36/python/cugraph/cugraph/sampling/uniform_neighbor_sample.py#L23-L50

**Comment by VibhuJawa** [comment] 2022-08-15 22:19
**MRE:**

```python

import cudf
import cugraph
import numpy as np

df = cudf.DataFrame({'source':[1,2,1,2],
                     'destination':[2,3,2,3]
                    })
df['eids']=np.arange(len(df))+10
df = df.astype(np.int32)


G = cugraph.Graph(directed=True)
G.from_cudf_edgelist(df,edge_attr='eids')

sample_df = cugraph.uniform_neighbor_sample(
    G,
    cudf.Series([1,3]),
    fanout_vals=[1,2],
    is_edge_ids=True
)
print(sample_df)
```
```
   indices  sources  destinations
0       10        1             2
1       11        2             3
```

**Comment by alexbarghi-nv** [comment] 2022-08-18 03:25
The C++ code operates only on vertices but I can always automatically get the start vertices from the provided edges.  Also shouldn't the expected result be:

   indices  sources  destinations
0        1        1             2

**Comment by VibhuJawa** [comment] 2022-08-18 15:54
> ```python
> import cudf
> import cugraph
> import numpy as np
> 
> df = cudf.DataFrame({'source':[1,1],
>                      'destination':[2,2],
>                      'eids':[0,1]
>                     })
> df = df.astype(np.int32)
> 
> 
> G = cugraph.Graph(directed=True)
> G.from_cudf_edgelist(df,edge_attr='eids')
> 
> sample_df = cugraph.uniform_neighbor_sample(
>     G,
>     cudf.Series([1]),
>     fanout_vals=[2],
>     is_edge_ids=True
> )
> print(sample_df)
> ```

Nope, i want both the edges. Index 0 and Index 1.  Maybe below example is easier to get my point across ?

The index_ids here are `10` and `11`  and I do not renumber to be clearer. 

```python
import cudf
import cugraph
import numpy as np

df = cudf.DataFrame({'source':[1,1],
                     'destination':[2,2],
                     'eids':[10,11]
                    })
df = df.astype(np.int32)


G = cugraph.Graph(directed=True)
G.from_cudf_edgelist(df,edge_attr='eids', renumber=False, legacy_renum_only=False)

sample_df = cugraph.uniform_neighbor_sample(
    G,
    cudf.Series([1]).astype(np.int32),
    fanout_vals=[2],
    is_edge_ids=True
)
print(sample_df)
````
```
   sources  destinations  indices
0        1             2       10
0        1             2       11
```

**Comment by alexbarghi-nv** [comment] 2022-08-18 15:57
Ok, so you want the current behavior, but with the `is_edge_ids` flag specifying whether the weights are edge ids rather than always assuming they are, correct?

**Comment by alexbarghi-nv** [comment] 2022-08-18 15:58
My interpretation was that if `is_edge_ids` was true, it should treat the start ids as edge ids and automatically select the vertices from those edges.

**Comment by VibhuJawa** [comment] 2022-08-18 16:07
> Ok, so you want the current behavior, but with the `is_edge_ids` flag specifying whether the weights are edge ids rather than always assuming they are, correct?

Yup. Thats my understanding and then treating `sources`, `destinations`,`edge_ids` as unique identifiers so that they are sampled.

**Comment by VibhuJawa** [comment] 2022-08-18 16:10
> My interpretation was that if `is_edge_ids` was true, it should treat the start ids as edge ids and automatically select the vertices from those edges.

Okay.  Yup, thats a viable understanding too .  I guess we really need a docstring here to clarify what this was supposed to do.

**Comment by alexbarghi-nv** [comment] 2022-08-18 16:18
ok, so there are 2 problems here:
1. You need to use `cugraph.MultiGraph` since `cugraph.Graph` will automatically drop duplicate edges
2. Apparently it ignores the duplicate edge even when using a `cugraph.MultiGraph` which is either a bug in plc graph creation or `uniform_neighbor_sample` itself.

**Comment by alexbarghi-nv** [comment] 2022-08-18 16:49
(2) is linked to the `count_and_remove_duplicates` call currently in the C++ code for `uniform_neighbor_sample`.
And I would say (1) is expected behavior that we won't fix.

**Comment by VibhuJawa** [comment] 2022-08-18 18:32
> (2) is linked to the `count_and_remove_duplicates` call currently in the C++ code for `uniform_neighbor_sample`. And I would say (1) is expected behavior that we won't fix.

Thanks for helping triage, I think we are now all in agreement.

**Closed** 2023-01-23 23:30 UTC
Labels: bug
