### ISSUE TITLE
[ENH] MG pipeline performance analysis

### ISSUE THREAD

**Issue by afender** [rapidsai/cugraph#1003] opened 2020-07-15 17:29 UTC
We should analyze the whole stack on 
- Twitter, and hibench bigdata(x2,x4...) 
- 2, 4, and more GPUs if available
- every step tarting from reading 

To do
- [ ] record results in a drive spreadsheet 
- [ ] fill issues if performance problems need to be addressed

This is for performance analysis and different than the multi-node testing issue.

**Comment by rlratzel** [comment] 2020-11-23 21:58
Closing as a duplicate of #1085

**Closed by rlratzel** 2020-11-23 21:58 UTC
Labels: 2 - In Progress, multi-GPU
