### ISSUE TITLE
[FEA]: Create a multi column dataset and add to the base test for every algorithm

### ISSUE THREAD

**Issue by acostadon** [rapidsai/cugraph#3900] opened 2023-09-29 11:46 UTC
Every algorithm should be testing that it can handle processing a Multi-Column dataset - this is really a test of the underlying renumbering service.

```[tasklist]
### Tasks
- [ ] Create a multi-column dataset
- [ ] Add the dataset of Datasets (data in S3 and metadate file create)
- [ ] Add the dataset to the standard dataset array
```

**Comment by BradReesWork** [comment] 2023-09-29 20:04
seems like a duplicate of #1575

**Closed** 2024-05-28 20:00 UTC
Labels: feature request
